apiVersion: v1
kind: Service
metadata:
  name: biz-application-service
  namespace: devopspoc
  labels:
    name: biz-application-service
spec:
  type: NodePort
  ports:
  - port: 9601
    nodePort: 30003
    targetPort: 9601
    protocol: TCP

  selector:
    name: biz-application
    deploymentType: BLUE
