apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: biz-application-virtualservice
  namespace: canary
spec:
  hosts:
  - biz-application
  http:
  - route:
    - destination:
        host: biz-application
        subset: biz-application-v1
      weight: 80
    - destination:
        host: biz-application
        subset: biz-application-v2
      weight: 20
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: biz-application-dr
  namespace: canary
spec:
  host: biz-application
  subsets:
  - name: biz-application-v1
    labels:
      version: biz-application-v1
  - name: biz-application-v2
    labels:
      version: biz-application-v2