apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: biz-application-virtualservice
  namespace: canary
spec:
  hosts:
  - biz-application
  http:
  - route:
    - destination:
        host: biz-application
        subset: biz-application-production
#      weight: 90
#    - destination:
#        host: biz-application
#        subset: biz-application-uat
#      weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: biz-application-dr
  namespace: canary
spec:
  host: biz-application
  subsets:
  - name: biz-application-production
    labels:
      version: biz-application-production
  - name: biz-application-uat
    labels:
      version: biz-application-uat