apiVersion: v1
kind: Namespace
metadata:
  name: ru-deployment
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: biz-application
  namespace: ru-deployment
  labels:
    name: biz-application
    service: biz-application-service
spec:
  replicas: 2
  minReadySeconds: 25
  selector:
    matchLabels:
      name: biz-application
      type: frontend
  template:
    metadata:
      labels:
        name: biz-application
        type: frontend
    spec:
      containers:
      - name: biz-application
        image: nisumpk/biz_application
        ports:
        - containerPort: 9601
        env:
        - name: SERVER_PORT
          value: -Dserver.port=9601
        - name: DISCOVERY_SERVER_URL
          value: "-Deureka.client.serviceUrl.defaultZone=http://discovery-server-service:7001/eureka/"
        command: ["java"]
        args: ["$(SERVER_PORT)", "$(DISCOVERY_SERVER_URL)", "-Deureka.instance.preferIpAddress=true", "-Deureka.instance.ipAddress=biz-application-service", "-jar", "/usr/src/biz-application-SNAPSHOT.jar"]

        readinessProbe:
          httpGet:
            path: /
          #  host: 127.0.0.1
            port: 9601
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
           tcpSocket:
             port: 9601
           #  host: 127.0.0.1
           initialDelaySeconds: 15
           periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: biz-application-service
  namespace: ru-deployment
  labels:
    name: biz-application-service
spec:
  type: NodePort
  ports:
  - port: 9601
    nodePort: 30054
    targetPort: 9601
    protocol: TCP

  selector:
    name: biz-application
